require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "crittercism-component"

COMPONENT = "crittercism-1.0.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "Crittercism-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Crittercism Component" \
		--summary="Performance Monitor, prioritize, troubleshoot, and trend your Xamarin Apps." \
		--publisher="Crittercism, Inc." \
		--website="http://crittercsim.com/" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/crittercism_128x128.png" \
		--icon="icons/crittercism_512x512.png" \
		--library="ios":"bin/CrittercismXam.dll" \
		--library="android":"bin/Crittercism.Android.dll" \
		--sample="iOS Sample. Demonstrates Awesomeness on iOS.":"../samples/CrittercismSample.iOS/CrittercismSample.iOS.sln" \
		--sample="Android Sample. Demonstrates Awesomeness on Android":"../samples/CrittercismSample.Android/CrittercismSample.Android.sln"
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end